AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  VerboseLog:
    Type: String
    Default: ''
    Description: 'Set to something to provide detailed logging'
Globals:
  Api:
    Cors:
      AllowHeaders: "'Content-Type'"
      AllowOrigin: "'*'"
      MaxAge: "'3600'"

Resources:
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-table.html
  PollingTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "pollId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "pollId"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"
      SSESpecification:
        SSEEnabled: true

  PollManagementFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: poll-management
      Handler: lambda.handler
      Runtime: nodejs14.x
      MemorySize: 512
      Timeout: 30
      Policies:
        - Statement:
          - Effect: Allow
            Action:
              # https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazondynamodb.html
              - dynamodb:GetItem
              - dynamodb:PutItem
              - dynamodb:UpdateItem
            Resource: !GetAtt PollingTable.Arn
      Environment:
        Variables:
          POLLINGTABLE: !Ref PollingTable
          DEBUG: !Ref VerboseLog
      Events:
        CreatePollEvent:
          Type: Api
          Properties:
            Path: /polls
            Method: put
        ReadPollEvent:
          Type: Api
          Properties:
            Path: /polls/{pollId}
            Method: get
        VoteEvent:
          Type: Api
          Properties:
            Path: /polls/{pollId}
            Method: post

Outputs:
  APIURL:
    Description: "API Endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
  POLLINGTABLE:
    Description: "DynamoDB table for polling"
    Value: !Ref PollingTable
